version: "3.7"

services:
  db:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "54321:5432"
  app:
    image: pddg/task_categorizer:latest
    env_file:
      - .env
    environment:
      DB_PORT: 5432
      DB_HOST: db
    volumes:
      - "./:/opt/task_categorizer"
    ports:
      - "8000:8000"
