# Generated by Django 3.0 on 2019-12-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='raw',
            field=models.TextField(default='', verbose_name='Raw task'),
            preserve_default=False,
        ),
    ]
