# Generated by Django 3.0 on 2019-12-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reason',
            field=models.TextField(choices=[('NS', 'サポートしていない操作である'), ('TC', '複雑になりすぎる'), ('CJ', '判断できない'), ('C', '互換性のため'), ('NC', '---')], default='NC', max_length=2, verbose_name='置き換え不可能である理由'),
        ),
    ]
