# Generated by Django 3.0 on 2019-12-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_answer_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleversion',
            name='min_ansible_version',
            field=models.CharField(default=None, max_length=10, verbose_name='最小Ansibleバージョン'),
            preserve_default=False,
        ),
    ]
