# Generated by Django 3.0.1 on 2019-12-19 07:10

from django.db import migrations
from django.contrib.postgres.operations import CryptoExtension


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_roleversion_min_ansible_version'),
    ]

    operations = [
        CryptoExtension()
    ]
