# Generated by Django 3.0.1 on 2019-12-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20191219_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='message',
            field=models.TextField(default='', verbose_name='備考'),
        ),
    ]
