# Generated by Django 3.0.1 on 2019-12-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20191222_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='備考'),
        ),
    ]
