# Generated by Django 3.0.1 on 2020-01-10 01:44

from django.db import migrations, models
from django.core.management import call_command
import django.db.models.deletion


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'categories.json', app_label='tasks', )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20191222_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='alternate_module',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='代替可能モジュール'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='reason',
            field=models.TextField(choices=[('NS', 'サポートしていない操作である'), ('TC', '複雑になりすぎる'), ('CJ', '判断できない'), ('C', '互換性のため'), ('B', 'モジュールがバグを含むため'), ('NC', '---')], default='NC', max_length=2, verbose_name='置き換え不可能である理由'),
        ),
        migrations.AddField(
            model_name='answer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='tasks.Category'),
        ),
        migrations.RunPython(load_fixture),
    ]
